### ISSUE TITLE
Firebase application keys are public

### ISSUE THREAD

**Issue by GabrielFleischer** [Drone3D-Team/Drone3D#40]
The keys of the application are currently public.
We should use private key to hide them

**Comment by jonasblanc** [comment]
https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public

Based on this, I concluded it was okay to have them public.

**Comment by GabrielFleischer** [comment]
That means people could use it in there own app.
I guess it isn't a problem
